[Service]
LoadCredentialEncrypted=
LoadCredentialEncrypted=borgmatic-root:/etc/credstore.encrypted/borgmatic-root
LoadCredentialEncrypted=borgmatic-home:/etc/credstore.encrypted/borgmatic-home


CapabilityBoundingSet=
CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_DAC_OVERRIDE CAP_NET_RAW CAP_SYS_ADMIN CAP_FOWNER CAP_CHOWN

ProtectHome=no
ReadWritePaths=/ /home/alpha /home/personal
