[DeviceDialog]
DecisionIsPermanent=false
DecisionMethod=0
DefaultDecision=1
DefaultDecisionTimeout=30
MaskSerialNumber=false
RandomizeWindowPosition=false
ShowRejectButton=false

[MainWindow]
ExitToTray=true
SaveSize=false

[Notifications]
Allowed=true
Blocked=true
IPCStatus=false
Inserted=true
Present=false
Rejected=true
Removed=true
