#!/usr/bin/env sh

IFACE="$1"
STATUS="$2"

ALLOWED_APS="SSN SNUC SSN-LG_2.4"
SHADOWSOCKS_CONFIG_PATH="/etc/shadowsocks-rust/config_tun.json"

if [ "$IFACE" = "$(jq -r '.outbound_bind_interface' <"$SHADOWSOCKS_CONFIG_PATH")" ]; then

  if [ "$STATUS" = "up" ]; then

    ssid=$(iw dev "$WIFI_IFACE" info | awk '/ssid/ {print $2}')

    case " $ALLOWED_APS " in
    *" $ssid "*)
      ip route add default dev "$(jq -r '.locals[] | select(.protocol=="tun") | .tun_interface_name' <"$SHADOWSOCKS_CONFIG_PATH")" metric 100
      ;;
    esac
  fi

elif [ "$STATUS" = "down" ]; then

  ip route del default dev "$(jq -r '.locals[] | select(.protocol=="tun") | .tun_interface_name' <"$SHADOWSOCKS_CONFIG_PATH")" metric 100
fi
