[mgr]

prepend_keymap = [
  { on = "d", run = "remove --permanently", desc = "Permanently delete selected files" },
  { on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
]
