#!/bin/bash

sshd

wifi_info=$(termux-wifi-connectioninfo)
printf "Started SSH Daemon

SSID: $(echo $wifi_info | jq -r .ssid)
IP: $(echo $wifi_info | jq -r .ip)
Port: 8022
" | termux-toast

termux-wake-lock
