[Login]
HandlePowerKey=suspend
HandleSuspendKey=suspend
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=suspend
PowerKeyIgnoreInhibited=no
SuspendKeyIgnoreInhibited=yes
HibernateKeyIgnoreInhibited=no
LidSwitchIgnoreInhibited=yes
