CPU_SCALING_GOVERNOR_ON_AC=powersave
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_SCALING_GOVERNOR_ON_SAV=powersave

CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_ENERGY_PERF_POLICY_ON_SAV=power

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
CPU_BOOST_ON_SAV=0

PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=balanced
PLATFORM_PROFILE_ON_SAV=low-power

# Restore
CPU_SCALING_MAX_FREQ_ON_AC=5134889
CPU_SCALING_MIN_FREQ_ON_AC=419175
CPU_SCALING_MAX_FREQ_ON_BAT=5134889
CPU_SCALING_MIN_FREQ_ON_BAT=419175
# CPU dependent - amd_pstate_lowest_nonlinear_freq
CPU_SCALING_MAX_FREQ_ON_SAV=1100334
CPU_SCALING_MIN_FREQ_ON_SAV=419175
