max-concurrent-downloads=1
max-connection-per-server=8
split=8
min-split-size=25M

continue=true
auto-file-renaming=false
allow-overwrite=false

max-tries=15
retry-wait=10
timeout=30
connect-timeout=15
lowest-speed-limit=10K
remote-time=true

file-allocation=falloc
disk-cache=64M

console-log-level=warn
summary-interval=30
