#!/usr/bin/env sh

# It looks at the commits just brought in, and if
# one of them has the string "submodule: " commit message,
# it runs the submodule update command.

# figure out the old HEAD before the merge
old_head="$(git rev-parse HEAD@\{1\})"
new_head="$(git rev-parse HEAD)"

# scan every new commit for our magic string
git log --format='%H' "$old_head..$new_head" | while read -r sha; do
  subject=$(git log -1 --format='%s' "$sha")
  if echo "$subject" | grep -q -i "submodule: "; then
    echo "Restoring git submodules to lockfile state"
    git submodule init && git submodule update >/dev/null
    break
  fi
done
